#!/usr/bin/env ruby

RAILS_ROOT = "#{File.dirname(__FILE__)}/.."

puts "* Copying database config from template"
`cp #{RAILS_ROOT}/config/database.example.yml #{RAILS_ROOT}/config/database.yml`

puts "* Adding submodules"
`git submodule init`
`git submodule update`

puts "* Generating rspec configs"
`./script/generate rspec`
`git add script/spec spec`
`git commit -m '* Generating configs for rspec'`

puts "** Finished setting up project"
